---
- name: Update all servers
  hosts: all

  tasks:
  - name: Ensure httpd installed
    package:
      name: apache2
      state: present

  - name: Ensure httpd started
    service:
      name: apache2
      state: started
      enabled: true

