---
- name: Update all servers
  hosts: all

  tasks:
  - name: Ensure httpd installed
    package:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"  

  - name: Ensure httpd started
    service:
      name: apache2
      state: started
      enabled: true
    when: ansible_distribution == "Ubuntu"

  - name: Ensure httpd installed
    package:
      name: httpd
      state: present
    when: ansible_distribution == "CentOS"

  - name: Ensure httpd started
    service:
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution == "CentOS"

