---
- name: Update all servers
  hosts: all
  become: true

  tasks:
  - name: Ensure file uodated
    copy:
      src: ubuntu.html 
      dest: /var/www/html/
    when: ansible_distribution == "Ubuntu"

  - name: Ensure file uodated
    copy:
      src: centos.html
      dest: /var/www/html/
    when: ansible_distribution == "CentOS"


  

